abstract class HomeState {}
class InitState extends HomeState{}
class OnChange extends HomeState{}
class DataSuccess extends HomeState{}
class DataError extends HomeState{}
class DataLoading extends HomeState{}
class GetAdsSuccess extends HomeState{}
class GetCategoriesSuccess extends HomeState{}
class GetCategoriesError extends HomeState{}
class GetCategoriesLoading extends HomeState{}
class GetAdsError extends HomeState{}
class GetAdsLoading extends HomeState{}
class GetProductsSuccess extends HomeState{}
class GetProductsError extends HomeState{}
class GetProductsLoading extends HomeState{}
class ChangeSuccess extends HomeState{}
class GetAllCategoriesSuccess extends HomeState{}
class GetAllCategoriesError extends HomeState{}
class GetAllCategoriesLoading extends HomeState{}
class AddCartSuccess extends HomeState{}
class CreateSuccess extends HomeState{}
class AddCartError extends HomeState{}
class AddCartLoading extends HomeState{}
class GetCartSuccess extends HomeState{}
class GetCartError extends HomeState{}
class GetCartLoading extends HomeState{}
class FetchDataSuccess extends HomeState{}
class FetchDataError extends HomeState{}
class FetchDataLoading extends HomeState{}
class FetchDataEmpty extends HomeState{}
class DeleteCartItemLoading extends HomeState{}
class DeleteCartItemSuccess extends HomeState{}
class DeleteCartItemError extends HomeState{}
class OrdersLoading extends HomeState{}
class OrdersSuccess extends HomeState{}
class OrdersError extends HomeState{}

class SumSuccess extends HomeState{}
class OrderListLoading extends HomeState{}
class OrderListSuccess extends HomeState{}
class OrderListError extends HomeState{}
class OrderLoading extends HomeState{}
class OrderSuccess extends HomeState{}
class OrderError extends HomeState{}
class TotalCalculated extends HomeState{
}