abstract class AuthState {}
class InitState extends AuthState{}
class LoginLoading extends AuthState{}
class LoginSuccess extends AuthState{}
class LoginError extends AuthState{}
class SignUpLoading extends AuthState{}
class SignUpSuccess extends AuthState{}
class SignUpError extends AuthState{}
class ShowPasswordSuccess extends AuthState{}
class PasswordResetLoading extends AuthState{}
class PasswordResetSuccess extends AuthState{}
class PasswordResetError extends AuthState{}